const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

class PDFGeneratorService {
  static async generateFormPDF(submission, outputPath) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 });
        const writeStream = fs.createWriteStream(outputPath);

        doc.pipe(writeStream);

        // Header
        doc.fontSize(20)
           .font('Helvetica-Bold')
           .text(submission.formTitle || 'Form Submission', { align: 'center' })
           .moveDown();

        // Submission details
        doc.fontSize(10)
           .font('Helvetica')
           .text('Submission ID: ' + submission._id, { align: 'right' })
           .text('Date: ' + new Date(submission.createdAt).toLocaleDateString(), { align: 'right' })
           .moveDown(2);

        // Divider line
        doc.moveTo(50, doc.y)
           .lineTo(550, doc.y)
           .stroke()
           .moveDown();

        // Form data
        doc.fontSize(14)
           .font('Helvetica-Bold')
           .text('Form Data', { underline: true })
           .moveDown();

        doc.fontSize(11).font('Helvetica');

        const data = submission.data instanceof Map 
          ? Object.fromEntries(submission.data) 
          : submission.data;

        Object.entries(data).forEach(([key, value]) => {
          const label = key.replace(/_/g, ' ')
                          .split(' ')
                          .map(w => w.charAt(0).toUpperCase() + w.slice(1))
                          .join(' ');
          
          doc.font('Helvetica-Bold')
             .text(label + ':', { continued: true })
             .font('Helvetica')
             .text(' ' + (value || 'N/A'))
             .moveDown(0.5);
        });

        // Footer
        doc.moveDown(2)
           .fontSize(8)
           .font('Helvetica')
           .text('Generated by Smart Form Filler', 50, doc.page.height - 50, {
             align: 'center'
           });

        doc.end();

        writeStream.on('finish', () => {
          resolve(outputPath);
        });

        writeStream.on('error', reject);

      } catch (error) {
        reject(error);
      }
    });
  }
}

module.exports = PDFGeneratorService;
